name: psp-dynamic-libraries
 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang automake autoconf zlib-dev python3 py3-pycryptodomex py3-ecdsa zip curl unzip sudo

      - name: Cloning and Building lastest pspsdk
        run: | 
          git clone https://github.com/pspdev/pspsdk

      - name: Bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: ya2d via psp-pacman
        run: |
          psp-pacman -Syyu --noconfirm
          psp-pacman -S ya2d --noconfirm

      - name: Update psp-cfw-sdk
        run: curl -OJL "https://github.com/pspdev/psp-cfw-sdk/releases/download/latest/psp-cfw-sdk.zip"
      
      - name: Extract psp-cfw-sdk
        run: sudo unzip -o psp-cfw-sdk.zip -d /

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build
        run:  make clean && make 

      - name: Compress
        run: |
          cd dist/LIBS
          zip -r ../LIBS.zip .
      
      - name: Upload
        uses: actions/upload-artifact@v7
        with: 
          name: psp-dynamic-libraries-release
          path: LIBS.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: psp-dynamic-libraries-release
          path: .
      - name:
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: psp-dynamic-libraries
          prerelease: false
          files: LIBS.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    

